version: 2

sources:
  - name: erp_northwind
    description: fonte sap vendas northwind
    tables:
      - name: categories
        columns:
          - name: category_id
            tests:
              - unique
              - not_null
      - name: products
        columns:
          - name: product_id
            tests:
              - unique
              - not_null        
      - name: suppliers
        columns:
          - name: supplier_id
            tests:
              - unique
              - not_null
      - name: employees
      - name: orders
        description: Uma linha por pedido (por NF). Inclui pedidos cancelados e deletados.
        columns:
        - name: order_id
          tests:
            - unique
            - not_null
      - name: orders_details