version: 2

sources:
  - name: erp_northwind
    description: fonte sap vendas northwind
    tables:
      - name: categories
        columns:
          - name: category_id
            tests:
              - unique
              - not_null
      - name: products
        columns:
          - name: product_id
            tests:
              - unique
              - not_null        
      - name: suppliers
        columns:
          - name: supplier_id
            tests:
              - unique
              - not_null
                  